### PR TITLE
Py3 support

### PR DESCRIPTION
**Pull request by brianjbuck**
Added support for Python 3.4. Although I haven't tried it this should also work for all Python 3.x versions.

### CODE REVIEW

**Comment by imsickofmaps** [comment]
@alexhayes any chance of landing and pushing this pypi?

**Comment by alexhayes** [comment]
Sure - I'll update pypi early tomorrow.

**Comment by imsickofmaps** [comment]
@alexhayes :ok_hand:

**Comment by alexhayes** [comment]
Version 0.2.0 has been released on PYPI - https://pypi.python.org/pypi/django-migration-fixture

Thanks for adding support for Python 3.

**Comment by imsickofmaps** [comment]
@alexhayes thanks! And yes :tada: @brianjbuck

**Pull request merged**
